<a href="https://colab.research.google.com/github/JoSeongrae/JSR/blob/main/3_26_2Days.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## 리스트는 []를 쓰고 수정이 가능하며, 첫 글자를 숫자로 사용할 수 없다 12 x,l2 O

In [2]:
MyFirstList = [3, 45, 56, 732]

In [3]:
MyFirstList

[3, 45, 56, 732]

In [5]:
type(MyFirstList)

list

In [7]:
ㅣ2 = ["hello", 24, True, 55.3]

In [9]:
ㅣ2

['hello', 24, True, 55.3]

In [17]:
l3 = [ 'how are you?' , 55, MyFirstList]

In [19]:
l3

['how are you?', 55, [3, 45, 56, 732]]

In [21]:
range(15)

range(0, 15)

In [22]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [25]:
x = list(range(8))

In [26]:
x

[0, 1, 2, 3, 4, 5, 6, 7]

In [27]:
z = list(range(1,8))

In [28]:
z

[1, 2, 3, 4, 5, 6, 7]

In [29]:
z2 = list(range(100,120))

In [30]:
z2

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119]

In [32]:
w = list(range(100, 111, 2))

In [33]:
w

[100, 102, 104, 106, 108, 110]

In [34]:
w2 = list(range(100, 111, 10))

In [35]:
w2

[100, 110]

In [36]:
w = ['a', 'b', 'c', 'd', 'e']

In [37]:
w

['a', 'b', 'c', 'd', 'e']

In [39]:
w[0]

'a'

In [40]:
w[1]

'b'

In [41]:
len(w)

5

In [42]:
w[5]

IndexError: list index out of range

In [43]:
w[4]

'e'

In [44]:
w

['a', 'b', 'c', 'd', 'e']

In [45]:
w[-1]

'e'

In [46]:
w[-4]

'b'

In [47]:
w

['a', 'b', 'c', 'd', 'e']

In [48]:
w[2] = 63

In [49]:
w

['a', 'b', 63, 'd', 'e']

In [55]:
w[2] = list(range(7))

In [56]:
w

['a', 'b', [0, 1, 2, 3, 4, 5, 6], 'd', 'e']

In [57]:
len(w)

5

In [58]:
len(w[2])

7

In [59]:
letters = ['A','B','C', 'D', 'E', 'F', 'G','H', 'I', 'J']

In [61]:
letters[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [62]:
letters[2:]

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [63]:
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [64]:
letters[2:7]

['C', 'D', 'E', 'F', 'G']

In [65]:
letters[-8 : 7]

['C', 'D', 'E', 'F', 'G']

In [66]:
letters[-8 : -3]

['C', 'D', 'E', 'F', 'G']

In [67]:
letters[-3 : -8]

[]

In [68]:
letters[2 : 9 : 2]

['C', 'E', 'G', 'I']

In [69]:
letters[ :  : -1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [70]:
letters[-3 : -8 : -1]

['H', 'G', 'F', 'E', 'D']

In [71]:
t1 = (345, 674, 934) ##튜플은 ()쓰고 수정이 불가하다

In [72]:
t1[0]

345

In [73]:
##Funtions(함수)

In [74]:
range(20, 31)

range(20, 31)

In [76]:
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [77]:
mylist1 =list(range(20,31))

In [78]:
mylist1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [79]:
print(mylist1)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [80]:
len(mylist1)

11

In [81]:
type(mylist1)

list

In [83]:
max(mylist1)

30

In [84]:
min(mylist1)

20

In [85]:
#Packages(패키지), Module

In [86]:
pip install scrapy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 43.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.8/259.8 kB 14.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.9/104.9 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.6/74.6 kB 5.5 MB/s eta 0:00:00


In [87]:
import numpy as np

In [88]:
import scrapy

In [89]:
from scrapy.crawler import CrawlerProcess

In [90]:
#numpy 배열(array) = 같은 종류의 데이터만 넣을 수 있음 ex) 정수(int), 문자(str) 등

In [91]:
l = [23245, 27 ,546, 215, -1234]

In [93]:
l

[23245, 27, 546, 215, -1234]

In [95]:
a = np.array(l)

In [96]:
a

array([23245,    27,   546,   215, -1234])

In [97]:
b = np.array(['12', '455', '63', 'True', 'abc'])

In [98]:
print(b)

['12' '455' '63' 'True' 'abc']


In [99]:
l.pop() #pop은 리스트의 마지막 값을 가져오며 이후 리스트 조회시 해당 값은 삭제 됌

-1234

In [100]:
l

[23245, 27, 546, 215]

In [102]:
a.mean() #mean은 값의 평균

np.float64(4559.8)

In [103]:
abc = np.array(l2)

NameError: name 'l2' is not defined

In [117]:
l2 = [11, "hello", 24, True, 55.3]

In [115]:
abc = np.array(l2) #array는 한 종류의 데이터만 기록이 가능하여 다른 종류의 리스트 데이터 입력시 문자나 숫자로 통일됌

In [118]:
print(abc)

[11.  24.   1.  55.3]


In [119]:
a

array([23245,    27,   546,   215, -1234])

In [120]:
a[2:4]

array([546, 215])

In [121]:
b = a[2:4]

In [122]:
b

array([546, 215])

In [123]:
b[0]

np.int64(546)

In [124]:
b[:] = 111

In [125]:
a #a를 슬라이스한 b의 데이터를 변경하면 a의 데이터도 같이 변경된다

array([23245,    27,   111,   111, -1234])